/**
 * Words that must never be flagged, even when a listed word appears inside
 * them. This is what keeps `match: "loose"` usable and protects ordinary
 * English, and real place names, from the classic false positives.
 *
 * `createTextFilter` uses this list by default, and `allow` adds to it.
 * Entries are matched loosely and must contain the match, so a stem such as
 * `analy` exempts "analysis" and "analyze" at once. An entry can only ever
 * prevent a match, never cause one.
 *
 * The package ships no list of words to match *against*. Which words a game
 * filters is its own editorial decision, the lists differ by audience and
 * language, and better-maintained ones exist; `words` is required for that
 * reason. This list is here because it is not that: it is ordinary English,
 * tuned to how this matcher treats stems and endings.
 */
export const defaultAllowList: readonly string[] = [
  "accumul",
  "analog",
  "analy",
  "arsenal",
  "assassin",
  "asset",
  "assign",
  "assist",
  "associate",
  "assume",
  "assure",
  "auspicious",
  "banal",
  "basement",
  "bass",
  "brass",
  "canal",
  "casement",
  "circumstance",
  "class",
  "classic",
  "clitheroe",
  "cockatoo",
  "cockney",
  "cockpit",
  "cocktail",
  "cocoon",
  "conspicuous",
  "cucumber",
  "cumbersome",
  "cumbria",
  "cumin",
  "cummerbund",
  "cummings",
  "cumquat",
  "cumulative",
  "cumulus",
  "dickens",
  "dickinson",
  "document",
  "drape",
  "easement",
  "essex",
  "grape",
  "grass",
  "hancock",
  "harass",
  "hitchcock",
  "manus",
  "mass",
  "massachusetts",
  "matsushita",
  "meacock",
  "middlesex",
  "pakistan",
  "pass",
  "password",
  "peacock",
  "penistone",
  "prickle",
  "prickly",
  "raccoon",
  "rapeseed",
  "resurrection",
  "scrape",
  "scum",
  "scunthorpe",
  "shiitake",
  "shitake",
  "spice",
  "spicy",
  "suspicio",
  "sussex",
  "therapist",
  "titan",
  "titanium",
  "title",
  "trapeze",
  "twatt",
  "tycoon",
  "uranus",
  "vacuum",
  "wankel",
];
